[package]
name = "beam-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.3.4", features = ["v4", "serde"] }

[features]
sockets = []
strict-ids = []
